version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt

commands:
  - sphinx-build -b html -D language=en -d _build/doctrees . $READTHEDOCS_OUTPUT/html
