# .readthedocs.yml

version: 2

build:
  # Remove the 'os' option since it's causing validation error
  # os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt
    - requirements: environment.yml

sphinx:
  configuration: docs/source/conf.py

# Include output directory configuration if needed
build:
  image: latest
  output_base: $READTHEDOCS_OUTPUT/html
