# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt
    - requirements: environment.yml
  system_packages: true

sphinx:
  configuration: docs/source/conf.py

build:
  image: latest