version: 2

build:
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt
    - requirements: environment.yml

sphinx:
  configuration: docs/source/conf.py

build:
  image: "latest"
  output_base: $READTHEDOCS_OUTPUT/html
