import os

project = 'Your Project Name'

# General configuration
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'myst_parser',
]

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

if not os.path.exists('_static'):
    os.makedirs('_static')

if os.getenv('READTHEDOCS', None) == 'True':
    html_output = os.getenv('READTHEDOCS_OUTPUT', '_build/html')
    html_output = os.getenv('READTHEDOCS_OUTPUT')
else:
    html_output = '_build/html'

html_output = os.getenv('READTHEDOCS_OUTPUT', '_build/html')
