title: Computing in Context - Hiroyuki
author: Hiroyuki

only_build_toc_files: true

execute:
  execute_notebooks: "off"

sphinx:
  config:
    # https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#implicit-targets
    myst_heading_anchors: 4